### ISSUE TITLE
Failing to import on Windows (using a a mingw build of libarchive)

### ISSUE THREAD

**Issue by pombreda** [Changaco/python-libarchive-c#2]
Here is the trace:
```
>>> import libarchive.ffi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\tst\lib\site-packages\libarchive\__init__.py", line 6, in <module>
    from .entry import ArchiveEntry
  File "c:\tst\lib\site-packages\libarchive\entry.py", line 11, in <module>
    from . import ffi
  File "c:\tst\lib\site-packages\libarchive\ffi.py", line 21, in <module>
    page_size = pythonapi.getpagesize()
  File "c:\Python27\Lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\Lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'getpagesize' not found
```

This fails here:
https://github.com/Changaco/python-libarchive-c/blob/master/libarchive/ffi.py#L21
getpagesize() is not a CPython function on non-posix builds.

I think the alternative to get the page size that is portable is to use mmap:
```
import mmap
mmap.PAGESIZE
```

**Comment by pombreda** [comment]
Thanks!
