### ISSUE TITLE
can't import libarchive after installation

### ISSUE THREAD

**Issue by mickeydonkey** [Changaco/python-libarchive-c#44]
OS: windows 10
python version: 3.5.2

I install it via `pip install libarchive-c `, here is the Error traceback:
```
(C:\Users\**\Miniconda3) C:\Users\**>python -c "import libarchive"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\**\Miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\**\Miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\**\Miniconda3\lib\site-packages\libarchive\ffi.py", line 21, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\**\Miniconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\**\Miniconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```

**Comment by krzysztofzuraw** [comment]
Do you have libarchive installed?

**Comment by bicobus** [comment]
libarchive cannot be installed in a windows environment, it needs to be built which defeats the purpose of using a python module in the first place.
