### ISSUE TITLE
Unrecognized archive format on 7z archive

### ISSUE THREAD

**Issue by superm1** [Changaco/python-libarchive-c#64]
I've used this in the past to be able to extract TBT updates.  At least this recent one it's stopped working.

Here is the (simple) script I'm using just to test the parsing:
```
#!/usr/bin/python3
import libarchive

filename='Intel_TBT3_FW_UPDATE_NVM28_3H3DP_A01_4.28.06.001.exe'

with libarchive.file_reader(filename) as e:
    for entry in e:
        print(str(entry))
```

However I just noticed it failing on some recent ones.
```
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    with libarchive.file_reader(filename) as e:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/supermario/.local/lib/python3.5/site-packages/libarchive/read.py", line 68, in file_reader
    ffi.read_open_filename_w(archive_p, path, block_size)
  File "/home/supermario/.local/lib/python3.5/site-packages/libarchive/ffi.py", line 88, in check_int
    raise archive_error(args[0], retcode)
  File "/home/supermario/.local/lib/python3.5/site-packages/libarchive/ffi.py", line 72, in archive_error
    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)
libarchive.exception.ArchiveError: Unrecognized archive format (errno=84, retcode=-30, archive_p=45795904)
```

Whereas it works with 7z:
```
# 7z x Intel_TBT3_FW_UPDATE_NVM28_3H3DP_A01_4.28.06.001.exe 

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,16 CPUs)

Processing archive: Intel_TBT3_FW_UPDATE_NVM28_3H3DP_A01_4.28.06.001.exe

Extracting  Intel/0x07E6_secure.bin
Extracting  Intel/FwUpdateCmd.exe
Extracting  Intel/FwUpdateApi.dll
Extracting  Intel

Everything is Ok

Folders: 1
Files: 3
Size:       342528
Compressed: 1102184
```

The file is available here: http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=3H3DP

I have libarchive 3.2.2-3.1 from [here](https://launchpad.net/ubuntu/+source/libarchive/3.2.2-3.1)
I have libarchive-c 2.7 from `pip3 install libarchive-c`

**Comment by Changaco** [comment]
I can confirm that I get the same error, but I can't do anything to fix it since it's not due to the python code. You should report the problem upstream to libarchive.

**Comment by superm1** [comment]
OK thanks for your confirmation, I'll report it there.
